### ISSUE TITLE
Partman stops all management operations if a table doesn't exist

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/mariadb-sequential-partition-manager-py#47]
I detected this after running the alter table and partman startup command in https://github.com/letsencrypt/mariadb-sequential-partition-manager-py/issues/46.
```
-- The job identifier is 496805.
May 20 19:55:17 mydb partition-manager[642828]: 2022-05-20 19:55:17,509 - all_configured_tables_are_compatible - ERROR - Cannot proceed: Table orderToAuthz2_new_20220419 ['Unable to read information for orderToAuthz2_new_20220419']
May 20 19:55:17 mydb systemd[1]: partition-manager.service: Succeeded.
-- Subject: Unit succeeded
```

The partman error text output leads me to believe that partman will fail to perform actually useful operations since this table no longer exists in my database. This could lead to a table overrun issues and we'd have to re-migrate tables **again**.

**Comment by jcjones** [comment]
`all_configured_tables_are_compatible` is only checked for the `migrate` command, not for `maintain`, so it should only affect operator-hands-on operations, not automated ones. Still, we should fix this.
